"""
PostgreSQL database layer for agency-os.

All persistence logic lives here. The rest of the system works with
dataclasses from core/models.py; this module translates between
dataclasses and SQL rows.
"""

from __future__ import annotations

import json
import os
import re
import threading
from contextlib import contextmanager
from functools import lru_cache
from datetime import datetime, timedelta
from typing import Iterator, Optional

import psycopg
from psycopg.types.string import TextLoader

from core import access
from core.access import AccessError, CurrentUser
from core.models import Prospect, Outreach, EmailLog, SendResult, EnrichmentResult, CallLog


SCHEMA = """
-- citext gives users.email and roles.name case-insensitive equality and uniqueness.
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS prospects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    ein TEXT,
    ntee_code TEXT,
    website_url TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    county TEXT,
    focus_area TEXT,
    annual_revenue BIGINT,
    voter_engagement INTEGER DEFAULT 0,
    source TEXT,
    source_url TEXT,
    metadata TEXT DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(ein)
);

CREATE TABLE IF NOT EXISTS campaigns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    config_path TEXT,
    is_active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS outreach (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prospect_id INTEGER NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    stage TEXT DEFAULT 'cold',
    touch_count INTEGER DEFAULT 0,
    contact_name TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    contact_title TEXT,
    script_variant TEXT,
    last_contacted_at TIMESTAMP,
    next_follow_up_at TIMESTAMP,
    demo_link TEXT,
    notes TEXT,
    activity_log TEXT DEFAULT '[]',
    assigned_to TEXT,
    closed_at TIMESTAMP,
    close_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(prospect_id, campaign_id)
);

CREATE TABLE IF NOT EXISTS email_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outreach_id INTEGER NOT NULL REFERENCES outreach(id) ON DELETE CASCADE,
    campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    template_key TEXT,
    subject TEXT,
    body TEXT,
    status TEXT,
    provider_message_id TEXT,
    sent_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outreach_stage ON outreach(stage);
CREATE INDEX IF NOT EXISTS idx_outreach_next_follow_up ON outreach(next_follow_up_at);
CREATE INDEX IF NOT EXISTS idx_outreach_campaign ON outreach(campaign_id);
CREATE INDEX IF NOT EXISTS idx_prospects_ein ON prospects(ein);
CREATE INDEX IF NOT EXISTS idx_prospects_county ON prospects(county);

CREATE TABLE IF NOT EXISTS call_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outreach_id INTEGER NOT NULL REFERENCES outreach(id) ON DELETE CASCADE,
    campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    prospect_id INTEGER NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    script_key TEXT,
    script_title TEXT,
    stage_at_call TEXT,
    outcome TEXT DEFAULT 'completed',
    duration_minutes INTEGER,
    interest_level TEXT,
    decision_maker_name TEXT,
    decision_maker_role TEXT,
    contact_method TEXT DEFAULT 'phone',
    next_step TEXT,
    next_step_date TIMESTAMP,
    voicemail_left INTEGER DEFAULT 0,
    notes TEXT,
    called_by TEXT,
    called_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_call_log_outreach ON call_log(outreach_id);
CREATE INDEX IF NOT EXISTS idx_call_log_prospect ON call_log(prospect_id);
CREATE INDEX IF NOT EXISTS idx_call_log_campaign ON call_log(campaign_id);
CREATE INDEX IF NOT EXISTS idx_call_log_called_at ON call_log(called_at);

CREATE TABLE IF NOT EXISTS product_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_key TEXT NOT NULL,
    event_id BIGINT NOT NULL,
    event_type TEXT,
    external_ref TEXT,
    data TEXT DEFAULT '{}',
    processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(product_key, event_id)
);

CREATE INDEX IF NOT EXISTS idx_product_events_key ON product_events(product_key);

-- Background job runs (core/jobs.py): what ran, when, and the result.
CREATE TABLE IF NOT EXISTS job_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job TEXT NOT NULL,
    trigger TEXT NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    ok INTEGER,
    summary TEXT
);

CREATE INDEX IF NOT EXISTS idx_job_runs_job ON job_runs(job, started_at);

CREATE TABLE IF NOT EXISTS sync_cursors (
    product_key TEXT PRIMARY KEY,
    cursor_value BIGINT DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email CITEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    is_active INTEGER DEFAULT 1,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prospect_saved_lists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 80),
    criteria TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CITEXT UNIQUE NOT NULL,
    description TEXT,
    is_protected INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission TEXT NOT NULL,
    PRIMARY KEY (role_id, permission)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS sessions (
    token_hash TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    actor_label TEXT NOT NULL,
    action TEXT NOT NULL,
    target_type TEXT,
    target_id TEXT,
    details TEXT DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- One-time "set your password" links sent in welcome emails
CREATE TABLE IF NOT EXISTS invites (
    token_hash TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP
);

-- Campaign YAMLs (campaign.yaml, scripts/*.yaml), keyed by path relative to the
-- campaigns dir. The source of truth; core/campaign.py writes them to disk to load.
CREATE TABLE IF NOT EXISTS campaign_files (
    path TEXT PRIMARY KEY,
    content TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);

-- Per-user settings. A missing row means defaults (no spending).
CREATE TABLE IF NOT EXISTS user_prefs (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    monthly_spend_allowance_atomic BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- x402 lead packages unlocked into a campaign (core/lead_packages.py).
-- Prices are USDC atomic units (6 decimals) as quoted by the provider's catalog.
CREATE TABLE IF NOT EXISTS lead_packages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    package_id TEXT NOT NULL,
    campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    title TEXT,
    industry TEXT,
    region TEXT,
    lead_count INTEGER DEFAULT 0,
    imported_count INTEGER DEFAULT 0,
    duplicate_count INTEGER DEFAULT 0,
    unlock_price_atomic BIGINT NOT NULL DEFAULT 0,
    royalty_atomic BIGINT NOT NULL DEFAULT 0,
    royalty_by_tier TEXT DEFAULT '{}',
    pay_to TEXT NOT NULL,
    network TEXT NOT NULL,
    guarantee TEXT DEFAULT '{}',
    guarantee_tier TEXT,
    consent_note TEXT,
    sms_consent INTEGER DEFAULT 0,
    unlocked_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    unlocked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tx_hash TEXT,
    UNIQUE (provider, package_id, campaign_id)
);

-- Columns added after lead_packages first shipped (no-ops on new databases).
ALTER TABLE lead_packages ADD COLUMN IF NOT EXISTS royalty_by_tier TEXT DEFAULT '{}';
ALTER TABLE lead_packages ADD COLUMN IF NOT EXISTS guarantee_tier TEXT;
-- The guarantee rules fixed at unlock (core/verify.Rules); NULL on older unlocks.
ALTER TABLE lead_packages ADD COLUMN IF NOT EXISTS guarantee_rules TEXT;
-- The seller's claim token from the unlock response; sent with guarantee claims.
ALTER TABLE lead_packages ADD COLUMN IF NOT EXISTS claim_token TEXT;
-- AI features are opt-in per user (Account page); a missing row means off.
ALTER TABLE user_prefs ADD COLUMN IF NOT EXISTS ai_enabled INTEGER NOT NULL DEFAULT 0;

-- Ledger of every x402 payment attempt. `ref` identifies what was bought
-- (provider/package for an unlock, provider/package/lead for a royalty).
CREATE TABLE IF NOT EXISTS spend (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    ref TEXT NOT NULL,
    campaign_id INTEGER REFERENCES campaigns(id) ON DELETE SET NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    prospect_id INTEGER REFERENCES prospects(id) ON DELETE SET NULL,
    lead_package_id INTEGER REFERENCES lead_packages(id) ON DELETE SET NULL,
    url TEXT,
    amount_atomic BIGINT NOT NULL DEFAULT 0,
    asset TEXT,
    network TEXT,
    pay_to TEXT,
    tx_hash TEXT,
    status TEXT NOT NULL,
    error TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Each unlock / royalty is payable once per campaign, even across workers.
CREATE UNIQUE INDEX IF NOT EXISTS idx_spend_once ON spend(kind, campaign_id, ref)
    WHERE status IN ('pending', 'settled');
CREATE INDEX IF NOT EXISTS idx_spend_campaign ON spend(campaign_id, created_at);
CREATE INDEX IF NOT EXISTS idx_spend_user ON spend(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_spend_prospect ON spend(prospect_id);

-- One row per package lead: the 90% guarantee's verdict on it (core/verify.py).
-- package_email is the address the seller supplied, kept for comparisons
-- after the contact is refreshed.
CREATE TABLE IF NOT EXISTS lead_checks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_package_id INTEGER NOT NULL REFERENCES lead_packages(id) ON DELETE CASCADE,
    prospect_id INTEGER NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    lead_id TEXT NOT NULL,
    seller_tier TEXT,
    package_email TEXT,
    replacement INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'unworked',
    score REAL NOT NULL DEFAULT 0,
    signals TEXT DEFAULT '[]',
    ai_verdict TEXT,
    ai_reason TEXT,
    ai_input_hash TEXT,
    claim_id INTEGER,
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (lead_package_id, prospect_id)
);
CREATE INDEX IF NOT EXISTS idx_lead_checks_prospect ON lead_checks(prospect_id);

-- Evidence about a contact that isn't a send or a call: bounces, returned
-- mail, enricher comparisons. Written by hand today, by webhooks later.
CREATE TABLE IF NOT EXISTS contact_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prospect_id INTEGER NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    campaign_id INTEGER REFERENCES campaigns(id) ON DELETE SET NULL,
    kind TEXT NOT NULL,
    value TEXT,
    detail TEXT DEFAULT '{}',
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_contact_events_prospect ON contact_events(prospect_id);

-- Guarantee claims we file against a package (core/claims.py).
CREATE TABLE IF NOT EXISTS package_claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_package_id INTEGER NOT NULL REFERENCES lead_packages(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    lead_count INTEGER NOT NULL,
    failed_count INTEGER NOT NULL,
    shortfall INTEGER NOT NULL,
    verified_rate REAL,
    expected_refund_atomic BIGINT NOT NULL DEFAULT 0,
    remedy TEXT,
    replacement_count INTEGER NOT NULL DEFAULT 0,
    refund_atomic BIGINT NOT NULL DEFAULT 0,
    refund_tx TEXT,
    reason TEXT,
    filed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_package_claims_package ON package_claims(lead_package_id);

-- Selling our own lists as x402 lead packages (core/selling.py).
-- do_not_sell: a person asked not to have their data sold (California Delete
-- Act); they're never published, sold or sent as a replacement.
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS do_not_sell INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS published_packages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    saved_list_id INTEGER REFERENCES prospect_saved_lists(id) ON DELETE SET NULL,
    criteria TEXT NOT NULL,
    title TEXT NOT NULL,
    industry TEXT,
    region TEXT,
    consent_note TEXT,
    sms_consent INTEGER NOT NULL DEFAULT 0,
    guarantee_tier TEXT NOT NULL,
    rules TEXT NOT NULL,
    unlock_price_atomic BIGINT NOT NULL,
    royalty_atomic BIGINT NOT NULL,
    royalty_by_tier TEXT NOT NULL DEFAULT '{}',
    contributor_pool_pct INTEGER NOT NULL DEFAULT 20,
    active INTEGER NOT NULL DEFAULT 1,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS published_leads (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id INTEGER NOT NULL REFERENCES published_packages(id) ON DELETE CASCADE,
    prospect_id INTEGER NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    lead_id TEXT NOT NULL UNIQUE,
    tier TEXT NOT NULL,
    replacement INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (package_id, prospect_id)
);
CREATE TABLE IF NOT EXISTS package_sales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id INTEGER NOT NULL REFERENCES published_packages(id) ON DELETE CASCADE,
    payer TEXT NOT NULL,
    network TEXT NOT NULL,
    tx_hash TEXT NOT NULL UNIQUE,
    amount_atomic BIGINT NOT NULL,
    claim_token_hash TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_package_sales_payer ON package_sales(package_id, payer);
CREATE TABLE IF NOT EXISTS sale_leads (
    sale_id INTEGER NOT NULL REFERENCES package_sales(id) ON DELETE CASCADE,
    published_lead_id INTEGER NOT NULL REFERENCES published_leads(id) ON DELETE CASCADE,
    replacement INTEGER NOT NULL DEFAULT 0,
    claim_id INTEGER,
    PRIMARY KEY (sale_id, published_lead_id)
);
CREATE TABLE IF NOT EXISTS sale_royalties (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INTEGER NOT NULL REFERENCES package_sales(id) ON DELETE CASCADE,
    published_lead_id INTEGER NOT NULL REFERENCES published_leads(id) ON DELETE CASCADE,
    tx_hash TEXT NOT NULL UNIQUE,
    amount_atomic BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (sale_id, published_lead_id)
);
CREATE TABLE IF NOT EXISTS incoming_claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INTEGER NOT NULL REFERENCES package_sales(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    shortfall INTEGER NOT NULL,
    failed TEXT NOT NULL,
    reason TEXT,
    replacement_count INTEGER NOT NULL DEFAULT 0,
    refund_atomic BIGINT NOT NULL DEFAULT 0,
    refund_tx TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP
);

-- Rep royalties for the leads we sell (core/royalties.py).
ALTER TABLE call_log ADD COLUMN IF NOT EXISTS called_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE user_prefs ADD COLUMN IF NOT EXISTS payout_address TEXT;
CREATE TABLE IF NOT EXISTS lead_contributions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prospect_id INTEGER NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    task TEXT NOT NULL,
    source TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (prospect_id, user_id, task)
);
CREATE TABLE IF NOT EXISTS rep_payouts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount_atomic BIGINT NOT NULL,
    address TEXT NOT NULL,
    network TEXT NOT NULL,
    tx_hash TEXT,
    status TEXT NOT NULL,
    error TEXT,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS rep_accruals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sale_id INTEGER NOT NULL REFERENCES package_sales(id) ON DELETE CASCADE,
    published_lead_id INTEGER NOT NULL REFERENCES published_leads(id) ON DELETE CASCADE,
    income TEXT NOT NULL,
    task TEXT NOT NULL,
    amount_atomic BIGINT NOT NULL,
    status TEXT NOT NULL,
    payable_at TIMESTAMP NOT NULL,
    payout_id INTEGER REFERENCES rep_payouts(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (sale_id, published_lead_id, income, user_id, task)
);
CREATE INDEX IF NOT EXISTS idx_rep_accruals_user ON rep_accruals(user_id, status);

-- Bearer tokens for MCP clients (core/mcp_auth.py). Only a SHA-256 hash is
-- stored. kind: personal (made on the Account page), access / refresh (OAuth).
-- An OAuth access and refresh token issued together share a family, so
-- revoking one revokes both.
CREATE TABLE IF NOT EXISTS api_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    name TEXT,
    token_hash TEXT NOT NULL UNIQUE,
    client_id TEXT NOT NULL,
    scopes TEXT NOT NULL,
    resource TEXT,
    family TEXT,
    expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP,
    revoked_at TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_api_tokens_user ON api_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_api_tokens_family ON api_tokens(family);

-- OAuth 2.1 for hosted assistants (Claude.ai, ChatGPT connectors).
CREATE TABLE IF NOT EXISTS oauth_clients (
    client_id TEXT PRIMARY KEY,
    info TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS oauth_requests (
    request_hash TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    params TEXT NOT NULL,
    expires_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS oauth_codes (
    code_hash TEXT PRIMARY KEY,
    client_id TEXT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scopes TEXT NOT NULL,
    code_challenge TEXT NOT NULL,
    redirect_uri TEXT NOT NULL,
    redirect_uri_explicit INTEGER NOT NULL,
    resource TEXT,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP
);

-- Prospect sources that cost money or have rate limits (core/source_budget.py).
CREATE TABLE IF NOT EXISTS source_usage (
    source TEXT NOT NULL,
    day DATE NOT NULL,
    requests INTEGER NOT NULL DEFAULT 0,
    cost_cents INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (source, day)
);
CREATE TABLE IF NOT EXISTS source_cache (
    source TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (source, key)
);
-- Campaign members: once a campaign has any, only they (people, or everyone in a role)
-- and Owners see it and its leads (CurrentUser.sees_campaign). Keyed by campaign name,
-- like hidden_clause, so a campaign file can be restricted before its first sync.
CREATE TABLE IF NOT EXISTS campaign_members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign TEXT NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    role_id INTEGER REFERENCES roles(id) ON DELETE CASCADE,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK ((user_id IS NULL) <> (role_id IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_campaign_members_user ON campaign_members(campaign, user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_campaign_members_role ON campaign_members(campaign, role_id) WHERE role_id IS NOT NULL;

-- Campaign owners: once a Super Admin assigns any, only those Owners (and Super Admins)
-- see and manage the campaign; other Owners don't know it exists (CurrentUser.sees_campaign).
CREATE TABLE IF NOT EXISTS campaign_owners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign TEXT NOT NULL,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (campaign, user_id)
);

-- Saved workflows: replayable recipes for the in-browser player (core/workflows.py).
CREATE TABLE IF NOT EXISTS workflows (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    slug TEXT NOT NULL,
    name TEXT NOT NULL,
    definition TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (owner_id, slug)
);
"""


# ── Connection ─────────────────────────────────────────────────────────
# Callers write SQL with "?" placeholders and read rows by column name or
# index, so Connection translates placeholders and Row keeps both access styles.
# Timestamps are read back as text ("2026-01-31 09:00:00") because the rest of
# the code parses them with datetime.fromisoformat.

_SCHEMA_LOCK_ID = 7_201_100  # advisory lock key: schema setup
_WRITE_LOCK_ID = 7_201_101   # advisory lock key: Database.transaction()


def database_url() -> str:
    """The configured DATABASE_URL (Railway sets it when Postgres is linked)."""
    url = os.environ.get("DATABASE_URL", "").strip()
    if not url:
        raise RuntimeError("DATABASE_URL is not set. Point it at a PostgreSQL database.")
    return url


def redact_url(url: str) -> str:
    """The URL with any password masked, for printing."""
    return re.sub(r"(://[^:/@]+:)[^@]*@", r"\1***@", url)


class Row(tuple):
    """Tuple row that can also be indexed by column name, like Row."""

    def __new__(cls, values, index: dict[str, int]):
        row = super().__new__(cls, values)
        row._index = index
        return row

    def __getitem__(self, key):
        if isinstance(key, str):
            return tuple.__getitem__(self, self._index[key])
        return tuple.__getitem__(self, key)

    def keys(self) -> list[str]:
        return list(self._index)


def _row_factory(cursor):
    index: dict[str, int] = {}
    for i, column in enumerate(cursor.description or ()):
        index.setdefault(column.name, i)  # first wins on duplicate names, like sqlite3
    return lambda values: Row(values, index)


@lru_cache(maxsize=512)
def _to_pg(sql: str) -> str:
    """Rewrite "?" placeholders to "%s" and escape literal "%", skipping quoted text."""
    out = []
    for i, part in enumerate(re.split(r"('(?:[^']|'')*')", sql)):
        part = part.replace("%", "%%")
        out.append(part if i % 2 else part.replace("?", "%s"))
    return "".join(out)


class Connection:
    """Autocommit psycopg connection with a sqlite3-style execute API."""

    def __init__(self, raw: psycopg.Connection):
        self.raw = raw

    def execute(self, sql: str, params=()) -> psycopg.Cursor:
        return self.raw.execute(_to_pg(sql), params or None)

    def executemany(self, sql: str, seq) -> None:
        seq = list(seq)
        if seq:
            with self.raw.cursor() as cur:
                cur.executemany(_to_pg(sql), seq)

    def commit(self) -> None:
        """No-op: statements autocommit; use Database.transaction() to group them."""


_local = threading.local()
_open_conns: list[Connection] = []  # every thread's, so reset_schema_cache can close them
_schema_ready: set[str] = set()
_schema_guard = threading.Lock()


def _connect(url: str) -> Connection:
    raw = psycopg.connect(url, autocommit=True, row_factory=_row_factory)
    for pg_type in ("timestamp", "timestamptz"):
        raw.adapters.register_loader(pg_type, TextLoader)
    raw.execute("SET TIME ZONE 'UTC'")  # CURRENT_TIMESTAMP in UTC, as SQLite did
    conn = Connection(raw)
    with _schema_guard:
        _open_conns[:] = [c for c in _open_conns if not c.raw.closed]
        _open_conns.append(conn)
    return conn


def _ensure_schema(conn: Connection, url: str) -> None:
    with _schema_guard:
        if url in _schema_ready:
            return
        with conn.raw.transaction():
            conn.execute("SELECT pg_advisory_xact_lock(?)", (_SCHEMA_LOCK_ID,))
            conn.raw.execute(SCHEMA)
        _schema_ready.add(url)


def reset_schema_cache() -> None:
    """Forget which databases have been set up and close open connections,
    whose cached type info goes stale (tests drop and recreate schemas)."""
    with _schema_guard:
        _schema_ready.clear()
        for conn in _open_conns:
            conn.raw.close()
        _open_conns.clear()


class Database:
    """Thin PostgreSQL wrapper with dataclass (de)serialization.

    Connections are reused per thread, so creating a Database is cheap.
    """

    def __init__(self, url: Optional[str] = None):
        self.url = url or database_url()

    @property
    def conn(self) -> Connection:
        conns = getattr(_local, "conns", None)
        if conns is None:
            conns = _local.conns = {}
        conn = conns.get(self.url)
        if conn is None or conn.raw.closed or conn.raw.broken:
            conn = conns[self.url] = _connect(self.url)
        _ensure_schema(conn, self.url)
        return conn

    @staticmethod
    def hidden_clause(hidden_campaigns, prospect_col: str = "p.id") -> tuple[str, list]:
        """SQL condition (and params) that drops prospects in any of `hidden_campaigns`
        (core.campaign.hidden_campaigns); "1=1" when nothing is hidden."""
        if not hidden_campaigns:
            return "1=1", []
        return (f"NOT EXISTS (SELECT 1 FROM outreach ho JOIN campaigns hc ON hc.id = ho.campaign_id "
                f"WHERE ho.prospect_id = {prospect_col} AND hc.name = ANY(?))", [list(hidden_campaigns)])

    def prospect_hidden(self, prospect_id: int, hidden_campaigns) -> bool:
        if not hidden_campaigns:
            return False
        clause, params = self.hidden_clause(hidden_campaigns, "?")
        return not self.conn.execute(f"SELECT {clause}", (prospect_id, *params)).fetchone()[0]

    @staticmethod
    def prospect_filter(criteria: dict, hidden_campaigns=()) -> tuple[str, list]:
        """WHERE clause (over prospects p LEFT JOIN outreach o) and params for the
        prospect list filters, as saved in prospect_saved_lists, without the
        prospects in hidden_campaigns."""
        where, params = [], []
        if hidden_campaigns:
            clause, hidden_params = Database.hidden_clause(hidden_campaigns)
            where.append(clause)
            params.extend(hidden_params)
        q = (criteria.get("q") or "").strip()
        if q:
            where.append("(p.name ILIKE ? OR p.city ILIKE ? OR p.ein ILIKE ? "
                         "OR p.zip ILIKE ? OR p.focus_area ILIKE ? OR p.website_url ILIKE ? "
                         "OR p.county ILIKE ? OR p.ntee_code ILIKE ?)")
            params.extend([f"%{q}%"] * 8)
        if criteria.get("source"):
            where.append("p.source = ?")
            params.append(criteria["source"])
        if criteria.get("stage"):
            where.append("o.stage = ?")
            params.append(criteria["stage"])
        if criteria.get("campaign"):
            where.append("o.campaign_id = (SELECT id FROM campaigns WHERE name = ?)")
            params.append(criteria["campaign"])
        cities = [c.strip() for c in (criteria.get("cities") or "").split(",") if c.strip()]
        if cities:
            where.append(f"p.city IN ({','.join('?' * len(cities))})")
            params.extend(cities)
        return (" AND ".join(where) if where else "1=1"), params

    def get_prospect_saved_list(self, list_id: int) -> Optional[dict]:
        row = self.conn.execute("SELECT * FROM prospect_saved_lists WHERE id = ?", (list_id,)).fetchone()
        if row is None:
            return None
        found = dict(row)
        found["criteria"] = json.loads(found["criteria"] or "{}")
        return found

    def list_prospect_saved_lists(self, user_id: int) -> list[dict]:
        rows = self.conn.execute(
            "SELECT id, name, criteria FROM prospect_saved_lists WHERE user_id = ? ORDER BY lower(name), id",
            (user_id,),
        ).fetchall()
        return [dict(id=r["id"], name=r["name"], criteria=json.loads(r["criteria"])) for r in rows]

    def save_prospect_list(self, user_id: int, name: str, criteria: dict) -> None:
        name = name.strip()
        if not 1 <= len(name) <= 80:
            raise ValueError("List name must be between 1 and 80 characters.")
        self.conn.execute(
            """INSERT INTO prospect_saved_lists (user_id, name, criteria) VALUES (?, ?, ?)
               ON CONFLICT (user_id, name) DO UPDATE
               SET criteria = EXCLUDED.criteria, updated_at = CURRENT_TIMESTAMP""",
            (user_id, name, json.dumps(criteria)),
        )
        self.conn.commit()

    def delete_prospect_saved_list(self, user_id: int, list_id: int) -> None:
        self.conn.execute("DELETE FROM prospect_saved_lists WHERE user_id = ? AND id = ?", (user_id, list_id))
        self.conn.commit()

    # ── Prospects ──────────────────────────────────────────────────────

    def upsert_prospect(self, p: Prospect) -> int:
        """Insert or update a prospect by its source's own id (metadata.external_ref,
        e.g. an NPI number), else EIN, else name+state."""
        c = self.conn
        external_ref = (p.metadata or {}).get("external_ref")
        if external_ref:
            row = c.execute(
                "SELECT id FROM prospects WHERE source = ? AND metadata::jsonb ->> 'external_ref' = ?",
                (p.source, str(external_ref)),
            ).fetchone()
        elif p.ein:
            row = c.execute("SELECT id FROM prospects WHERE ein = ?", (p.ein,)).fetchone()
        else:
            row = c.execute(
                "SELECT id FROM prospects WHERE name = ? AND state = ?",
                (p.name, p.state),
            ).fetchone()

        if row:
            c.execute(
                """UPDATE prospects SET name=?, ein=?, ntee_code=?, website_url=?,
                   address=?, city=?, state=?, zip=?, county=?, focus_area=?,
                   annual_revenue=?, voter_engagement=?, source=?, source_url=?,
                   metadata=?, updated_at=CURRENT_TIMESTAMP WHERE id=?""",
                (
                    p.name, p.ein, p.ntee_code, p.website_url,
                    p.address, p.city, p.state, p.zip, p.county, p.focus_area,
                    p.annual_revenue, int(p.voter_engagement), p.source, p.source_url,
                    json.dumps(p.metadata), row["id"],
                ),
            )
            return row["id"]

        cur = c.execute(
            """INSERT INTO prospects (name, ein, ntee_code, website_url, address,
               city, state, zip, county, focus_area, annual_revenue,
               voter_engagement, source, source_url, metadata)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id""",
            (
                p.name, p.ein, p.ntee_code, p.website_url, p.address,
                p.city, p.state, p.zip, p.county, p.focus_area,
                p.annual_revenue, int(p.voter_engagement), p.source, p.source_url,
                json.dumps(p.metadata),
            ),
        )
        return cur.fetchone()["id"]

    def get_prospect(self, prospect_id: int) -> Optional[Prospect]:
        row = self.conn.execute("SELECT * FROM prospects WHERE id = ?", (prospect_id,)).fetchone()
        return self._row_to_prospect(row) if row else None

    def _row_to_prospect(self, row: Row) -> Prospect:
        return Prospect(
            id=row["id"],
            name=row["name"],
            ein=row["ein"],
            ntee_code=row["ntee_code"],
            website_url=row["website_url"],
            address=row["address"],
            city=row["city"],
            state=row["state"],
            zip=row["zip"],
            county=row["county"],
            focus_area=row["focus_area"],
            annual_revenue=row["annual_revenue"],
            voter_engagement=bool(row["voter_engagement"]),
            source=row["source"],
            source_url=row["source_url"],
            metadata=json.loads(row["metadata"] or "{}"),
            created_at=datetime.fromisoformat(row["created_at"]) if row["created_at"] else None,
            updated_at=datetime.fromisoformat(row["updated_at"]) if row["updated_at"] else None,
        )

    # ── Campaigns ──────────────────────────────────────────────────────

    def upsert_campaign(self, name: str, config_path: str) -> int:
        c = self.conn
        row = c.execute("SELECT id FROM campaigns WHERE name = ?", (name,)).fetchone()
        if row:
            c.execute("UPDATE campaigns SET config_path=? WHERE id=?", (config_path, row["id"]))
            return row["id"]
        cur = c.execute(
            "INSERT INTO campaigns (name, config_path) VALUES (?, ?) RETURNING id", (name, config_path)
        )
        return cur.fetchone()["id"]

    def get_campaign_id(self, name: str) -> Optional[int]:
        row = self.conn.execute("SELECT id FROM campaigns WHERE name = ?", (name,)).fetchone()
        return row["id"] if row else None

    # ── Campaign files ─────────────────────────────────────────────────

    def campaign_files(self) -> dict[str, str]:
        rows = self.conn.execute("SELECT path, content FROM campaign_files").fetchall()
        return {r["path"]: r["content"] for r in rows}

    def save_campaign_file(self, path: str, content: str) -> None:
        self.conn.execute(
            """INSERT INTO campaign_files (path, content) VALUES (?, ?)
               ON CONFLICT (path) DO UPDATE SET content = excluded.content,
                                                updated_at = CURRENT_TIMESTAMP""",
            (path, content),
        )

    def seed_campaign_files(self, files: dict[str, str]) -> int:
        """Add files that aren't stored yet; never overwrites edits. Returns count added."""
        added = 0
        for path, content in files.items():
            added += self.conn.execute(
                "INSERT INTO campaign_files (path, content) VALUES (?, ?) ON CONFLICT DO NOTHING",
                (path, content),
            ).rowcount
        return added

    # ── Outreach ───────────────────────────────────────────────────────

    def upsert_outreach(self, prospect_id: int, campaign_id: int) -> int:
        """Create an outreach row if it doesn't exist (idempotent)."""
        c = self.conn
        row = c.execute(
            "SELECT id FROM outreach WHERE prospect_id = ? AND campaign_id = ?",
            (prospect_id, campaign_id),
        ).fetchone()
        if row:
            return row["id"]
        cur = c.execute(
            """INSERT INTO outreach (prospect_id, campaign_id, stage, touch_count)
               VALUES (?, ?, 'cold', 0) RETURNING id""",
            (prospect_id, campaign_id),
        )
        return cur.fetchone()["id"]

    def seed_contact(self, outreach_id: int, contact: dict) -> None:
        """Fill a source's own contact details (e.g. an NPI listing's phone and
        authorized official) into the outreach row's empty fields only, so a
        rep's edits and enrichment results are never overwritten."""
        values = [str(contact.get(k) or "").strip()[:300] or None
                  for k in ("name", "email", "phone", "title")]
        self.conn.execute(
            """UPDATE outreach SET contact_name = COALESCE(contact_name, ?),
                      contact_email = COALESCE(contact_email, ?),
                      contact_phone = COALESCE(contact_phone, ?),
                      contact_title = COALESCE(contact_title, ?) WHERE id = ?""",
            (*values, outreach_id))

    def get_outreach(self, outreach_id: int) -> Optional[Outreach]:
        row = self.conn.execute("SELECT * FROM outreach WHERE id = ?", (outreach_id,)).fetchone()
        return self._row_to_outreach(row) if row else None

    def get_due_outreach(self, campaign_name: str, limit: int = 50,
                         stages: Optional[list[str]] = None) -> list[Outreach]:
        """Get outreach rows that are due for a follow-up touch.

        If `stages` is given, only rows in those stages are returned (so e.g.
        prospects who booked a demo drop out of the automated sequence).
        """
        c = self.conn
        stage_sql, stage_params = "", []
        if stages:
            stage_sql = f"AND o.stage IN ({','.join('?' * len(stages))})"
            stage_params = list(stages)
        rows = c.execute(
            f"""SELECT o.* FROM outreach o
               JOIN campaigns c ON o.campaign_id = c.id
               WHERE c.name = ?
                 AND o.stage NOT IN ('closed_won', 'closed_lost', 'nurture')
                 {stage_sql}
                 AND (o.next_follow_up_at IS NULL OR o.next_follow_up_at <= CURRENT_TIMESTAMP)
               ORDER BY COALESCE(o.next_follow_up_at, '1970-01-01') ASC
               LIMIT ?""",
            (campaign_name, *stage_params, limit),
        ).fetchall()
        return [self._row_to_outreach(r) for r in rows]

    def find_outreach_by_email(self, campaign_name: str, email: str) -> Optional[Outreach]:
        """Find a campaign's outreach row by contact email (case-insensitive)."""
        row = self.conn.execute(
            """SELECT o.* FROM outreach o
               JOIN campaigns c ON o.campaign_id = c.id
               WHERE c.name = ? AND LOWER(o.contact_email) = LOWER(?)
               ORDER BY o.updated_at DESC LIMIT 1""",
            (campaign_name, email),
        ).fetchone()
        return self._row_to_outreach(row) if row else None

    def update_outreach(self, outreach_id: int, updates: dict) -> None:
        c = self.conn
        allowed = [
            "stage", "touch_count", "contact_name", "contact_email", "contact_phone",
            "contact_title", "script_variant", "last_contacted_at", "next_follow_up_at",
            "demo_link", "notes", "activity_log", "assigned_to", "closed_at", "close_reason",
        ]
        sets = []
        vals = []
        for k, v in updates.items():
            if k not in allowed:
                continue
            if k == "activity_log" and isinstance(v, list):
                v = json.dumps(v)
            sets.append(f"{k} = ?")
            vals.append(v)
        sets.append("updated_at = CURRENT_TIMESTAMP")
        vals.append(outreach_id)
        c.execute(f"UPDATE outreach SET {', '.join(sets)} WHERE id = ?", vals)

    def get_all_outreach_by_stage(self, campaign_name: str) -> dict[str, int]:
        c = self.conn
        rows = c.execute(
            """SELECT o.stage, COUNT(*) as cnt FROM outreach o
               JOIN campaigns c ON o.campaign_id = c.id
               WHERE c.name = ? GROUP BY o.stage""",
            (campaign_name,),
        ).fetchall()
        return {r["stage"]: r["cnt"] for r in rows}

    def move_stale_to_nurture(self, campaign_name: str, stale_days: int) -> int:
        """Move prospects with no contact in N days to nurture. Returns count moved."""
        c = self.conn
        cur = c.execute(
            """UPDATE outreach SET stage = 'nurture', updated_at = CURRENT_TIMESTAMP
               WHERE id IN (
                 SELECT o.id FROM outreach o
                 JOIN campaigns c ON o.campaign_id = c.id
                 WHERE c.name = ?
                   AND o.stage NOT IN ('closed_won', 'closed_lost', 'nurture')
                   AND o.last_contacted_at IS NOT NULL
                   AND o.last_contacted_at < LOCALTIMESTAMP - make_interval(days => ?)
               )""",
            (campaign_name, stale_days),
        )
        return cur.rowcount

    def _row_to_outreach(self, row: Row) -> Outreach:
        return Outreach(
            id=row["id"],
            prospect_id=row["prospect_id"],
            campaign_id=row["campaign_id"],
            stage=row["stage"],
            touch_count=row["touch_count"],
            contact_name=row["contact_name"],
            contact_email=row["contact_email"],
            contact_phone=row["contact_phone"],
            contact_title=row["contact_title"],
            script_variant=row["script_variant"],
            last_contacted_at=datetime.fromisoformat(row["last_contacted_at"]) if row["last_contacted_at"] else None,
            next_follow_up_at=datetime.fromisoformat(row["next_follow_up_at"]) if row["next_follow_up_at"] else None,
            demo_link=row["demo_link"],
            notes=row["notes"],
            activity_log=json.loads(row["activity_log"] or "[]"),
            assigned_to=row["assigned_to"],
            closed_at=datetime.fromisoformat(row["closed_at"]) if row["closed_at"] else None,
            close_reason=row["close_reason"],
            created_at=datetime.fromisoformat(row["created_at"]) if row["created_at"] else None,
            updated_at=datetime.fromisoformat(row["updated_at"]) if row["updated_at"] else None,
        )

    # ── Email Log ──────────────────────────────────────────────────────

    def log_email(
        self, outreach_id: int, campaign_id: int, template_key: str,
        subject: str, body: str, result: SendResult,
    ) -> int:
        cur = self.conn.execute(
            """INSERT INTO email_log (outreach_id, campaign_id, template_key,
               subject, body, status, provider_message_id, sent_at)
               VALUES (?,?,?,?,?,?,?,?) RETURNING id""",
            (
                outreach_id, campaign_id, template_key, subject, body,
                result.status, result.provider_message_id,
                (result.sent_at or datetime.now()).isoformat(),
            ),
        )
        return cur.fetchone()["id"]

    def get_pipeline_stats(self, campaign_name: str) -> dict:
        c = self.conn
        stage_counts = self.get_all_outreach_by_stage(campaign_name)
        total_prospects = c.execute(
            """SELECT COUNT(*) FROM outreach o
               JOIN campaigns c ON o.campaign_id = c.id WHERE c.name = ?""",
            (campaign_name,),
        ).fetchone()[0]
        total_emails = c.execute(
            """SELECT COUNT(*) FROM email_log e
               JOIN campaigns c ON e.campaign_id = c.id WHERE c.name = ?""",
            (campaign_name,),
        ).fetchone()[0]
        opened = c.execute(
            """SELECT COUNT(*) FROM email_log e
               JOIN campaigns c ON e.campaign_id = c.id
               WHERE c.name = ? AND e.status = 'opened'""",
            (campaign_name,),
        ).fetchone()[0]
        replied = c.execute(
            """SELECT COUNT(*) FROM email_log e
               JOIN campaigns c ON e.campaign_id = c.id
               WHERE c.name = ? AND e.status = 'replied'""",
            (campaign_name,),
        ).fetchone()[0]
        return {
            "campaign": campaign_name,
            "total_prospects": total_prospects,
            "total_emails_sent": total_emails,
            "stage_counts": stage_counts,
            "open_rate": f"{(opened / total_emails * 100):.1f}%" if total_emails else "0%",
            "reply_rate": f"{(replied / total_emails * 100):.1f}%" if total_emails else "0%",
        }

    # ── Enrichment ─────────────────────────────────────────────────────

    def apply_enrichment(self, outreach_id: int, result: EnrichmentResult, prospect_id: int = None) -> None:
        c = self.conn
        updates = {}
        if result.contact_name:
            updates["contact_name"] = result.contact_name
        if result.contact_email:
            updates["contact_email"] = result.contact_email
        if result.contact_phone:
            updates["contact_phone"] = result.contact_phone
        if result.contact_title:
            updates["contact_title"] = result.contact_title
        if updates:
            self.update_outreach(outreach_id, updates)

        # If the enricher discovered a website, save it back to the prospect
        if prospect_id and result.raw.get("website"):
            existing = c.execute(
                "SELECT website_url FROM prospects WHERE id = ?", (prospect_id,)
            ).fetchone()
            if existing and not existing["website_url"]:
                c.execute(
                    "UPDATE prospects SET website_url = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
                    (result.raw["website"], prospect_id),
                )

    def get_upcoming_events(self, days: int = 90, hidden_campaigns=()) -> list[dict]:
        """Get all upcoming follow-ups and call next-steps as calendar events."""
        c = self.conn
        hidden, hidden_params = self.hidden_clause(hidden_campaigns)
        cutoff = (datetime.now() + timedelta(days=days)).isoformat()
        now = datetime.now().isoformat()

        events = []

        # 1. Email follow-ups (next_follow_up_at from outreach)
        rows = c.execute(
            """SELECT o.id, o.next_follow_up_at, o.stage, o.touch_count,
                      o.contact_name, p.id as prospect_id, p.name as prospect_name,
                      p.city, p.state, c.name as campaign_name
               FROM outreach o
               JOIN prospects p ON o.prospect_id = p.id
               JOIN campaigns c ON o.campaign_id = c.id
               WHERE o.next_follow_up_at IS NOT NULL
                 AND o.next_follow_up_at > ?
                 AND o.next_follow_up_at < ?
                 AND o.stage NOT IN ('closed_won', 'closed_lost', 'nurture')
                 AND {hidden}
               ORDER BY o.next_follow_up_at ASC""".format(hidden=hidden),
            (now, cutoff, *hidden_params),
        ).fetchall()

        for r in rows:
            try:
                start = datetime.fromisoformat(r["next_follow_up_at"])
            except (ValueError, TypeError):
                continue

            touch_label = f" (touch {r['touch_count']})" if r["touch_count"] else ""
            events.append({
                "uid": f"followup-{r['id']}",
                "title": f"📧 Follow-up: {r['prospect_name']}{touch_label}",
                "description": (
                    f"Prospect: {r['prospect_name']}\n"
                    f"Stage: {r['stage']}\n"
                    f"Touch #: {r['touch_count']}\n"
                    f"Contact: {r['contact_name'] or 'N/A'}\n"
                    f"Campaign: {r['campaign_name']}\n"
                    f"Link: http://localhost:8000/prospects/{r['prospect_id']}"
                ),
                "start": start,
                "end": start + timedelta(minutes=15),
                "location": f"{r['city'] or ''}, {r['state'] or ''}".strip(", "),
                "type": "followup",
                "prospect_id": r["prospect_id"],
                "prospect_name": r["prospect_name"],
                "date": start,
            })

        # 2. Call next-step dates from call_log
        call_rows = c.execute(
            """SELECT cl.id, cl.next_step_date, cl.next_step, cl.outcome,
                      cl.interest_level, cl.script_title, cl.called_by,
                      p.id as prospect_id, p.name as prospect_name,
                      p.city, p.state
               FROM call_log cl
               JOIN prospects p ON cl.prospect_id = p.id
               WHERE cl.next_step_date IS NOT NULL
                 AND cl.next_step_date > ?
                 AND cl.next_step_date < ?
                 AND {hidden}
               ORDER BY cl.next_step_date ASC""".format(hidden=hidden),
            (now, cutoff, *hidden_params),
        ).fetchall()

        for r in call_rows:
            try:
                start = datetime.fromisoformat(r["next_step_date"])
            except (ValueError, TypeError):
                continue

            events.append({
                "uid": f"call-{r['id']}",
                "title": f"📞 {r['next_step'] or 'Call follow-up'}: {r['prospect_name']}",
                "description": (
                    f"Prospect: {r['prospect_name']}\n"
                    f"Next step: {r['next_step']}\n"
                    f"Previous call outcome: {r['outcome']}\n"
                    f"Interest: {r['interest_level'] or 'N/A'}\n"
                    f"Script used: {r['script_title'] or 'N/A'}\n"
                    f"Called by: {r['called_by'] or 'N/A'}\n"
                    f"Link: http://localhost:8000/prospects/{r['prospect_id']}"
                ),
                "start": start,
                "end": start + timedelta(minutes=30),
                "location": f"{r['city'] or ''}, {r['state'] or ''}".strip(", "),
                "type": "call",
                "prospect_id": r["prospect_id"],
                "prospect_name": r["prospect_name"],
                "date": start,
            })

        # Sort all events by date
        events.sort(key=lambda e: e["date"])
        return events

    def get_upcoming_events_for_prospect(self, prospect_id: int, days: int = 90) -> list[dict]:
        """Get upcoming events for a specific prospect."""
        all_events = self.get_upcoming_events(days)
        return [e for e in all_events if e.get("prospect_id") == prospect_id]

    # ── Call Log ───────────────────────────────────────────────────────

    def log_call(self, call: CallLog) -> int:
        """Insert a call log record and update the outreach row."""
        c = self.conn
        cur = c.execute(
            """INSERT INTO call_log
               (outreach_id, campaign_id, prospect_id, script_key, script_title,
                stage_at_call, outcome, duration_minutes, interest_level,
                decision_maker_name, decision_maker_role, contact_method,
                next_step, next_step_date, voicemail_left, notes, called_by, called_by_user_id)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id""",
            (
                call.outreach_id, call.campaign_id, call.prospect_id,
                call.script_key, call.script_title, call.stage_at_call,
                call.outcome, call.duration_minutes, call.interest_level,
                call.decision_maker_name, call.decision_maker_role,
                call.contact_method, call.next_step,
                call.next_step_date.isoformat() if call.next_step_date else None,
                int(call.voicemail_left), call.notes, call.called_by, call.called_by_user_id,
            ),
        )
        call_id = cur.fetchone()["id"]

        # Update outreach row based on call outcome
        updates = {"last_contacted_at": datetime.now().isoformat()}
        if call.outcome == "completed" and call.interest_level:
            if call.interest_level == "high":
                updates["stage"] = "engaged"
            elif call.interest_level in ("medium", "low"):
                updates["stage"] = "contacted"
            elif call.interest_level == "not_interested":
                updates["stage"] = "closed_lost"
                updates["closed_at"] = datetime.now().isoformat()
                if call.notes:
                    updates["close_reason"] = call.notes
        elif call.outcome in ("voicemail", "no_answer", "answering_machine", "busy", "hung_up"):
            updates["stage"] = "contacted"
        elif call.outcome == "scheduled":
            updates["stage"] = "demo_scheduled"

        if call.next_step_date:
            updates["next_follow_up_at"] = call.next_step_date.isoformat()

        if call.decision_maker_name and not call.decision_maker_name.startswith("("):
            updates["contact_name"] = call.decision_maker_name

        self.update_outreach(call.outreach_id, updates)

        return call_id

    def get_calls_for_prospect(self, prospect_id: int) -> list:
        """Get all call logs for a prospect, newest first."""
        rows = self.conn.execute(
            """SELECT cl.*, p.name as prospect_name, c.name as campaign_name
               FROM call_log cl
               JOIN prospects p ON cl.prospect_id = p.id
               JOIN campaigns c ON cl.campaign_id = c.id
               WHERE cl.prospect_id = ?
               ORDER BY cl.called_at DESC""",
            (prospect_id,),
        ).fetchall()
        return rows

    def get_all_calls(self, limit: int = 100, offset: int = 0,
                      outcome: str = "", interest: str = "", hidden_campaigns=()) -> list:
        """Get all call logs, newest first, with optional filters."""
        where_parts = []
        params = []
        if hidden_campaigns:
            clause, hidden_params = self.hidden_clause(hidden_campaigns, "cl.prospect_id")
            where_parts.append(clause)
            params.extend(hidden_params)
        if outcome:
            where_parts.append("cl.outcome = ?")
            params.append(outcome)
        if interest:
            where_parts.append("cl.interest_level = ?")
            params.append(interest)
        where_clause = " AND ".join(where_parts) if where_parts else "1=1"

        rows = self.conn.execute(
            f"""SELECT cl.*, p.name as prospect_name, p.city as prospect_city,
               c.name as campaign_name
               FROM call_log cl
               JOIN prospects p ON cl.prospect_id = p.id
               JOIN campaigns c ON cl.campaign_id = c.id
               WHERE {where_clause}
               ORDER BY cl.called_at DESC
               LIMIT ? OFFSET ?""",
            params + [limit, offset],
        ).fetchall()
        return rows

    def get_call_stats(self, campaign_name: str = "", hidden_campaigns=()) -> dict:
        """Aggregate call statistics."""
        c = self.conn
        hidden, params = self.hidden_clause(hidden_campaigns, "cl.prospect_id")
        where = f"WHERE {hidden}"
        if campaign_name:
            where += " AND c.name = ?"
            params = params + [campaign_name]

        total = c.execute(
            f"""SELECT COUNT(*) FROM call_log cl
               JOIN campaigns c ON cl.campaign_id = c.id {where}""",
            params,
        ).fetchone()[0]

        by_outcome = {}
        rows = c.execute(
            f"""SELECT cl.outcome, COUNT(*) as cnt FROM call_log cl
               JOIN campaigns c ON cl.campaign_id = c.id {where}
               GROUP BY cl.outcome""",
            params,
        ).fetchall()
        for r in rows:
            by_outcome[r["outcome"]] = r["cnt"]

        by_interest = {}
        rows = c.execute(
            f"""SELECT cl.interest_level, COUNT(*) as cnt FROM call_log cl
               JOIN campaigns c ON cl.campaign_id = c.id {where}
               AND cl.interest_level IS NOT NULL
               GROUP BY cl.interest_level""",
            params,
        ).fetchall()
        for r in rows:
            by_interest[r["interest_level"]] = r["cnt"]

        total_minutes = c.execute(
            f"""SELECT COALESCE(SUM(cl.duration_minutes), 0) FROM call_log cl
               JOIN campaigns c ON cl.campaign_id = c.id {where}""",
            params,
        ).fetchone()[0]

        return {
            "total_calls": total,
            "by_outcome": by_outcome,
            "by_interest": by_interest,
            "total_minutes": total_minutes,
        }

    # ── Users, roles & sessions ────────────────────────────────────────
    # Policy (catalog, route rules, password hashing) lives in core/access.py.

    @contextmanager
    def transaction(self) -> Iterator[Connection]:
        """Write transaction that takes a global write lock up front, so
        invariant checks like "at least one active owner" can't race."""
        c = self.conn
        with c.raw.transaction():
            c.execute("SELECT pg_advisory_xact_lock(?)", (_WRITE_LOCK_ID,))
            yield c

    def install_access(self) -> None:
        """Create the protected Owner and Super Admin roles and any missing starter roles.

        Idempotent. Never touches a role that already exists, so owner edits
        to starter roles survive restarts.
        """
        with self.transaction() as c:
            c.execute(
                """INSERT INTO roles (name, description, is_protected) VALUES (?, ?, 1)
                   ON CONFLICT DO NOTHING""",
                (access.OWNER_ROLE, "Full access, including managing users and roles"),
            )
            c.execute(
                """INSERT INTO roles (name, description, is_protected) VALUES (?, ?, 1)
                   ON CONFLICT DO NOTHING""",
                (access.SUPER_ADMIN_ROLE, "Everything an Owner can do, plus creating and promoting Owners"),
            )
            for name, (description, permissions) in access.STARTER_ROLES.items():
                created = c.execute(
                    """INSERT INTO roles (name, description) VALUES (?, ?)
                       ON CONFLICT DO NOTHING RETURNING id""",
                    (name, description),
                ).fetchone()
                if created:
                    c.executemany(
                        "INSERT INTO role_permissions (role_id, permission) VALUES (?, ?)",
                        [(created["id"], p) for p in permissions],
                    )

    def _audit(self, c: Connection, actor: Optional[CurrentUser], action: str,
               target_type: str = None, target_id=None, details: dict = None) -> None:
        c.execute(
            """INSERT INTO audit_log (actor_id, actor_label, action, target_type, target_id, details)
               VALUES (?, ?, ?, ?, ?, ?)""",
            (
                actor.id if actor else None,
                actor.email if actor else "cli",
                action, target_type,
                str(target_id) if target_id is not None else None,
                json.dumps(details or {}, default=str),
            ),
        )

    def audit(self, actor: Optional[CurrentUser], action: str,
              target_type: str = None, target_id=None, details: dict = None) -> None:
        """Record an audited action outside a larger transaction."""
        with self.transaction() as c:
            self._audit(c, actor, action, target_type, target_id, details)

    def list_audit(self, limit: int = 200) -> list:
        return self.conn.execute(
            "SELECT * FROM audit_log ORDER BY id DESC LIMIT ?", (limit,)
        ).fetchall()

    # Users

    def count_users(self) -> int:
        return self.conn.execute("SELECT COUNT(*) FROM users").fetchone()[0]

    def get_user_by_email(self, email: str):
        return self.conn.execute(
            "SELECT * FROM users WHERE email = ?", (email.strip(),)
        ).fetchone()

    def load_current_user(self, user_id: int) -> Optional[CurrentUser]:
        """Load an active user with roles and effective permissions.

        Called on every request, so role/permission changes and deactivation
        take effect on the user's very next request.
        """
        c = self.conn
        row = c.execute(
            "SELECT id, email, name FROM users WHERE id = ? AND is_active = 1", (user_id,)
        ).fetchone()
        if not row:
            return None
        roles = c.execute(
            """SELECT r.name FROM roles r JOIN user_roles ur ON ur.role_id = r.id
               WHERE ur.user_id = ? ORDER BY r.name""",
            (user_id,),
        ).fetchall()
        perms = c.execute(
            """SELECT DISTINCT rp.permission FROM role_permissions rp
               JOIN user_roles ur ON ur.role_id = rp.role_id WHERE ur.user_id = ?""",
            (user_id,),
        ).fetchall()
        prefs = c.execute("SELECT ai_enabled FROM user_prefs WHERE user_id = ?", (user_id,)).fetchone()
        members = c.execute(
            """SELECT campaign, (user_id = ? OR role_id IN (SELECT role_id FROM user_roles WHERE user_id = ?))
                      AS mine
               FROM campaign_members""", (user_id, user_id)).fetchall()
        owned = c.execute("SELECT campaign, user_id = ? AS mine FROM campaign_owners", (user_id,)).fetchall()
        return CurrentUser(
            id=row["id"], email=row["email"], name=row["name"],
            roles=tuple(r["name"] for r in roles),
            permissions=frozenset(p["permission"] for p in perms),
            ai_enabled=bool(prefs and prefs["ai_enabled"]),
            restricted_campaigns=frozenset(m["campaign"] for m in members),
            member_campaigns=frozenset(m["campaign"] for m in members if m["mine"]),
            owner_restricted_campaigns=frozenset(o["campaign"] for o in owned),
            owner_campaigns=frozenset(o["campaign"] for o in owned if o["mine"]),
        )

    # Campaign owners (which Owners run a campaign; Super Admins assign them)

    def campaign_owners(self, campaign: Optional[str] = None) -> list[dict]:
        sql = """SELECT o.id, o.campaign, o.user_id, o.added_at, u.name, u.email, u.is_active
                 FROM campaign_owners o JOIN users u ON u.id = o.user_id"""
        params: tuple = ()
        if campaign is not None:
            sql += " WHERE o.campaign = ?"
            params = (campaign,)
        return [dict(r) for r in self.conn.execute(sql + " ORDER BY u.name", params).fetchall()]

    @staticmethod
    def _guard_campaign_owners(actor: Optional[CurrentUser]) -> None:
        if actor is not None and not actor.is_super_admin:
            raise AccessError("Only a Super Admin can assign Owners to a campaign.")

    def add_campaign_owner(self, campaign: str, user_id: int, actor: Optional[CurrentUser]) -> bool:
        """Assign an Owner to a campaign. False if they already were."""
        self._guard_campaign_owners(actor)
        with self.transaction() as c:
            if access.OWNER_ROLE not in self._user_role_names(c, user_id):
                raise AccessError("Only people with the Owner role can be assigned as a campaign's Owner.")
            added = c.execute("""INSERT INTO campaign_owners (campaign, user_id) VALUES (?, ?)
                                 ON CONFLICT DO NOTHING RETURNING id""", (campaign, user_id)).fetchone()
            if added:
                self._audit(c, actor, "campaign.owner_add", "campaign", campaign, {"user_id": user_id})
        return added is not None

    def remove_campaign_owner(self, campaign: str, owner_id: int, actor: Optional[CurrentUser]) -> bool:
        self._guard_campaign_owners(actor)
        with self.transaction() as c:
            gone = c.execute("DELETE FROM campaign_owners WHERE id = ? AND campaign = ? RETURNING user_id",
                             (owner_id, campaign)).fetchone()
            if gone:
                self._audit(c, actor, "campaign.owner_remove", "campaign", campaign, {"user_id": gone["user_id"]})
        return gone is not None

    # Campaign members (who works a campaign; see CurrentUser.sees_campaign)

    def campaign_members(self, campaign: Optional[str] = None) -> list[dict]:
        """Members of one campaign (or all), with the person's or role's name."""
        sql = """SELECT m.id, m.campaign, m.user_id, m.role_id, m.added_at,
                        COALESCE(u.name, r.name) AS name, u.email, u.is_active
                 FROM campaign_members m
                 LEFT JOIN users u ON u.id = m.user_id LEFT JOIN roles r ON r.id = m.role_id"""
        params: tuple = ()
        if campaign is not None:
            sql += " WHERE m.campaign = ?"
            params = (campaign,)
        rows = self.conn.execute(sql + " ORDER BY m.role_id IS NULL, name", params).fetchall()
        return [{**dict(r), "kind": "role" if r["role_id"] else "user"} for r in rows]

    def add_campaign_member(self, campaign: str, actor: Optional[CurrentUser], *,
                            user_id: Optional[int] = None, role_id: Optional[int] = None) -> bool:
        """Add a person or a role to a campaign. False if they were already on it."""
        if (user_id is None) == (role_id is None):
            raise AccessError("Pick a person or a role.")
        with self.transaction() as c:
            table, key = ("users", user_id) if user_id is not None else ("roles", role_id)
            if not c.execute(f"SELECT 1 FROM {table} WHERE id = ?", (key,)).fetchone():
                raise AccessError("That person or role doesn't exist.")
            added = c.execute(
                """INSERT INTO campaign_members (campaign, user_id, role_id) VALUES (?, ?, ?)
                   ON CONFLICT DO NOTHING RETURNING id""", (campaign, user_id, role_id)).fetchone()
            if added:
                self._audit(c, actor, "campaign.member_add", "campaign", campaign,
                            {"user_id": user_id, "role_id": role_id})
        return added is not None

    def remove_campaign_member(self, campaign: str, member_id: int, actor: Optional[CurrentUser]) -> bool:
        with self.transaction() as c:
            gone = c.execute("DELETE FROM campaign_members WHERE id = ? AND campaign = ? RETURNING user_id, role_id",
                             (member_id, campaign)).fetchone()
            if gone:
                self._audit(c, actor, "campaign.member_remove", "campaign", campaign, dict(gone))
        return gone is not None

    def list_users(self) -> list[dict]:
        c = self.conn
        users = [dict(r) for r in c.execute(
            "SELECT id, email, name, is_active, last_login_at, created_at FROM users ORDER BY name"
        ).fetchall()]
        links = c.execute("SELECT user_id, role_id FROM user_roles").fetchall()
        for u in users:
            u["role_ids"] = {link["role_id"] for link in links if link["user_id"] == u["id"]}
        return users

    def _active_owner_count(self, c: Connection) -> int:
        return c.execute(
            """SELECT COUNT(DISTINCT u.id) FROM users u
               JOIN user_roles ur ON ur.user_id = u.id
               JOIN roles r ON r.id = ur.role_id
               WHERE r.name IN (?, ?) AND u.is_active = 1""",
            access.PROTECTED_ROLES,
        ).fetchone()[0]

    @staticmethod
    def _guard_protected(actor: Optional[CurrentUser], before: list[str], after: list[str]) -> None:
        """Only a Super Admin (or the server-side CLI, actor=None) may touch Owner/Super Admin.

        That covers granting or removing either role, and any change to a
        Super Admin's account.
        """
        if actor is None or actor.is_super_admin:
            return
        if access.SUPER_ADMIN_ROLE in before:
            raise AccessError("Only a Super Admin can change a Super Admin's account.")
        protected = set(access.PROTECTED_ROLES)
        if protected & set(before) != protected & set(after):
            raise AccessError("Only a Super Admin can grant or remove the Owner or Super Admin role.")

    def _user_role_names(self, c: Connection, user_id: int) -> list[str]:
        return [r["name"] for r in c.execute(
            """SELECT r.name FROM roles r JOIN user_roles ur ON ur.role_id = r.id
               WHERE ur.user_id = ? ORDER BY r.name""",
            (user_id,),
        ).fetchall()]

    def create_user(self, email: str, name: str, password: str, role_ids: list[int],
                    actor: Optional[CurrentUser]) -> int:
        email, name = email.strip().lower(), name.strip()
        if "@" not in email or not name:
            raise AccessError("A valid email and a name are required.")
        problem = access.password_problem(password)
        if problem:
            raise AccessError(problem)
        with self.transaction() as c:
            if c.execute("SELECT 1 FROM users WHERE email = ?", (email,)).fetchone():
                raise AccessError(f"A user with email {email} already exists.")
            cur = c.execute(
                "INSERT INTO users (email, name, password_hash) VALUES (?, ?, ?) RETURNING id",
                (email, name, access.hash_password(password)),
            )
            user_id = cur.fetchone()["id"]
            self._set_roles(c, user_id, role_ids)
            self._guard_protected(actor, [], self._user_role_names(c, user_id))
            self._audit(c, actor, "user.create", "user", user_id, {
                "email": email, "name": name, "roles": self._user_role_names(c, user_id),
            })
        return user_id

    def update_user(self, user_id: int, *, name: str, is_active: bool, role_ids: list[int],
                    actor: Optional[CurrentUser]) -> None:
        """Change a user's name, active flag, and roles in one audited step.

        Rejected if it would leave no active owner.
        """
        name = name.strip()
        if not name:
            raise AccessError("Name is required.")
        with self.transaction() as c:
            before = c.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
            if not before:
                raise AccessError("User not found.")
            roles_before = self._user_role_names(c, user_id)
            c.execute(
                "UPDATE users SET name = ?, is_active = ? WHERE id = ?",
                (name, int(is_active), user_id),
            )
            self._set_roles(c, user_id, role_ids)
            self._guard_protected(actor, roles_before, self._user_role_names(c, user_id))
            if self._active_owner_count(c) == 0:
                raise AccessError("At least one active Owner is required.")
            if not is_active:
                c.execute("DELETE FROM sessions WHERE user_id = ?", (user_id,))
            self._audit(c, actor, "user.update", "user", user_id, {
                "before": {"name": before["name"], "is_active": bool(before["is_active"]),
                           "roles": roles_before},
                "after": {"name": name, "is_active": is_active,
                          "roles": self._user_role_names(c, user_id)},
            })

    def _set_roles(self, c: Connection, user_id: int, role_ids: list[int]) -> None:
        role_ids = sorted(set(role_ids))
        if role_ids:
            found = c.execute(
                f"SELECT COUNT(*) FROM roles WHERE id IN ({','.join('?' * len(role_ids))})",
                role_ids,
            ).fetchone()[0]
            if found != len(role_ids):
                raise AccessError("Unknown role.")
        c.execute("DELETE FROM user_roles WHERE user_id = ?", (user_id,))
        c.executemany(
            "INSERT INTO user_roles (user_id, role_id) VALUES (?, ?)",
            [(user_id, r) for r in role_ids],
        )

    def set_password(self, user_id: int, password: str, actor: Optional[CurrentUser],
                     keep_session_hash: str = None) -> None:
        """Set a password and sign out every other session for that user."""
        problem = access.password_problem(password)
        if problem:
            raise AccessError(problem)
        with self.transaction() as c:
            c.execute(
                "UPDATE users SET password_hash = ? WHERE id = ?",
                (access.hash_password(password), user_id),
            )
            c.execute(
                "DELETE FROM sessions WHERE user_id = ? AND token_hash IS DISTINCT FROM ?",
                (user_id, keep_session_hash),
            )
            self._audit(c, actor, "user.password", "user", user_id)

    def grant_owner(self, email: str, actor: Optional[CurrentUser], role: str = access.OWNER_ROLE) -> None:
        """Recovery path (CLI only): make an existing user an active Owner (or Super Admin)."""
        with self.transaction() as c:
            row = c.execute("SELECT id FROM users WHERE email = ?", (email.strip(),)).fetchone()
            if not row:
                raise AccessError(f"No user with email {email}.")
            owner_role = c.execute(
                "SELECT id FROM roles WHERE name = ?", (role,)
            ).fetchone()
            self._guard_protected(actor, self._user_role_names(c, row["id"]), [role])
            c.execute("UPDATE users SET is_active = 1 WHERE id = ?", (row["id"],))
            c.execute(
                "INSERT INTO user_roles (user_id, role_id) VALUES (?, ?) ON CONFLICT DO NOTHING",
                (row["id"], owner_role["id"]),
            )
            self._audit(c, actor, "user.grant_owner", "user", row["id"], {"email": email, "role": role})

    # Roles

    def list_roles(self) -> list[dict]:
        c = self.conn
        roles = [dict(r) for r in c.execute(
            """SELECT r.*, (SELECT COUNT(*) FROM user_roles ur WHERE ur.role_id = r.id) AS user_count
               FROM roles r ORDER BY r.is_protected DESC, r.name"""
        ).fetchall()]
        perms = c.execute("SELECT role_id, permission FROM role_permissions").fetchall()
        for r in roles:
            r["permissions"] = {p["permission"] for p in perms if p["role_id"] == r["id"]}
        return roles

    def _validate_role(self, name: str, permissions: list[str]) -> tuple[str, list[str]]:
        name = name.strip()
        if not name:
            raise AccessError("Role name is required.")
        unknown = set(permissions) - set(access.CATALOG)
        if unknown:
            raise AccessError(f"Unknown permission(s): {', '.join(sorted(unknown))}")
        return name, sorted(set(permissions))

    def create_role(self, name: str, description: str, permissions: list[str],
                    actor: Optional[CurrentUser]) -> int:
        name, permissions = self._validate_role(name, permissions)
        with self.transaction() as c:
            if c.execute("SELECT 1 FROM roles WHERE name = ?", (name,)).fetchone():
                raise AccessError(f"A role named {name} already exists.")
            role_id = c.execute(
                "INSERT INTO roles (name, description) VALUES (?, ?) RETURNING id",
                (name, description.strip()),
            ).fetchone()["id"]
            c.executemany(
                "INSERT INTO role_permissions (role_id, permission) VALUES (?, ?)",
                [(role_id, p) for p in permissions],
            )
            self._audit(c, actor, "role.create", "role", role_id,
                        {"name": name, "permissions": permissions})
        return role_id

    def update_role(self, role_id: int, name: str, description: str, permissions: list[str],
                    actor: Optional[CurrentUser]) -> None:
        name, permissions = self._validate_role(name, permissions)
        with self.transaction() as c:
            before = c.execute("SELECT * FROM roles WHERE id = ?", (role_id,)).fetchone()
            if not before:
                raise AccessError("Role not found.")
            if before["is_protected"]:
                raise AccessError(f"The {before['name']} role is protected and can't be edited.")
            if c.execute(
                "SELECT 1 FROM roles WHERE name = ? AND id != ?", (name, role_id)
            ).fetchone():
                raise AccessError(f"A role named {name} already exists.")
            perms_before = sorted(r["permission"] for r in c.execute(
                "SELECT permission FROM role_permissions WHERE role_id = ?", (role_id,)
            ).fetchall())
            c.execute(
                "UPDATE roles SET name = ?, description = ? WHERE id = ?",
                (name, description.strip(), role_id),
            )
            c.execute("DELETE FROM role_permissions WHERE role_id = ?", (role_id,))
            c.executemany(
                "INSERT INTO role_permissions (role_id, permission) VALUES (?, ?)",
                [(role_id, p) for p in permissions],
            )
            self._audit(c, actor, "role.update", "role", role_id, {
                "before": {"name": before["name"], "permissions": perms_before},
                "after": {"name": name, "permissions": permissions},
            })

    def delete_role(self, role_id: int, actor: Optional[CurrentUser]) -> None:
        with self.transaction() as c:
            role = c.execute("SELECT * FROM roles WHERE id = ?", (role_id,)).fetchone()
            if not role:
                raise AccessError("Role not found.")
            if role["is_protected"]:
                raise AccessError(f"The {role['name']} role is protected and can't be deleted.")
            holders = [r["email"] for r in c.execute(
                """SELECT u.email FROM users u JOIN user_roles ur ON ur.user_id = u.id
                   WHERE ur.role_id = ?""",
                (role_id,),
            ).fetchall()]
            c.execute("DELETE FROM roles WHERE id = ?", (role_id,))
            self._audit(c, actor, "role.delete", "role", role_id,
                        {"name": role["name"], "removed_from": holders})

    # Sessions

    def create_session(self, user_id: int, token_hash: str, ttl_days: int) -> None:
        with self.transaction() as c:
            c.execute(
                "INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (?, ?, ?)",
                (token_hash, user_id, (datetime.now() + timedelta(days=ttl_days)).isoformat()),
            )
            c.execute(
                "UPDATE users SET last_login_at = CURRENT_TIMESTAMP WHERE id = ?", (user_id,)
            )
            c.execute("DELETE FROM sessions WHERE expires_at < ?", (datetime.now().isoformat(),))

    def session_user_id(self, token_hash: str) -> Optional[int]:
        row = self.conn.execute(
            "SELECT user_id FROM sessions WHERE token_hash = ? AND expires_at > ?",
            (token_hash, datetime.now().isoformat()),
        ).fetchone()
        return row["user_id"] if row else None

    def delete_session(self, token_hash: str) -> None:
        self.conn.execute("DELETE FROM sessions WHERE token_hash = ?", (token_hash,))

    # Invites (welcome-email "set your password" links)

    def create_invite(self, user_id: int, token_hash: str, ttl_days: int,
                      actor: Optional[CurrentUser]) -> datetime:
        """Issue a one-time password-setup link. Earlier unused links stop working."""
        expires_at = datetime.now() + timedelta(days=ttl_days)
        with self.transaction() as c:
            row = c.execute("SELECT email, is_active FROM users WHERE id = ?", (user_id,)).fetchone()
            if not row:
                raise AccessError("User not found.")
            if not row["is_active"]:
                raise AccessError(f"{row['email']} is deactivated; reactivate them first.")
            c.execute("DELETE FROM invites WHERE user_id = ? AND used_at IS NULL", (user_id,))
            c.execute(
                "INSERT INTO invites (token_hash, user_id, expires_at) VALUES (?, ?, ?)",
                (token_hash, user_id, expires_at.isoformat()),
            )
            self._audit(c, actor, "user.invite", "user", user_id,
                        {"email": row["email"], "expires_at": expires_at.isoformat()})
        return expires_at

    def invite_user_id(self, token_hash: str) -> Optional[int]:
        """The invited user's id if the link is unused, unexpired, and they're active."""
        row = self.conn.execute(
            """SELECT i.user_id FROM invites i JOIN users u ON u.id = i.user_id
               WHERE i.token_hash = ? AND i.used_at IS NULL AND i.expires_at > ?
                 AND u.is_active = 1""",
            (token_hash, datetime.now().isoformat()),
        ).fetchone()
        return row["user_id"] if row else None

    def accept_invite(self, token_hash: str, password: str) -> int:
        """Set the invited user's password, burn the link, and end old sessions."""
        problem = access.password_problem(password)
        if problem:
            raise AccessError(problem)
        with self.transaction() as c:
            row = c.execute(
                """SELECT i.user_id FROM invites i JOIN users u ON u.id = i.user_id
                   WHERE i.token_hash = ? AND i.used_at IS NULL AND i.expires_at > ?
                     AND u.is_active = 1""",
                (token_hash, datetime.now().isoformat()),
            ).fetchone()
            if not row:
                raise AccessError("This link has expired or was already used.")
            user_id = row["user_id"]
            c.execute("UPDATE users SET password_hash = ? WHERE id = ?",
                      (access.hash_password(password), user_id))
            c.execute("UPDATE invites SET used_at = CURRENT_TIMESTAMP WHERE token_hash = ?",
                      (token_hash,))
            c.execute("DELETE FROM invites WHERE user_id = ? AND used_at IS NULL", (user_id,))
            c.execute("DELETE FROM sessions WHERE user_id = ?", (user_id,))
        return user_id

    # ── Lead packages & spend (core/lead_packages.py, core/payments.py) ─

    def find_prospect_id(self, ein: Optional[str], name: str, state: Optional[str]) -> Optional[int]:
        """The existing prospect upsert_prospect would match, without writing."""
        if ein:
            row = self.conn.execute("SELECT id FROM prospects WHERE ein = ?", (ein,)).fetchone()
        else:
            row = self.conn.execute(
                "SELECT id FROM prospects WHERE name = ? AND state = ?", (name, state),
            ).fetchone()
        return row["id"] if row else None

    def get_lead_package(self, lead_package_id: int) -> Optional[dict]:
        row = self.conn.execute(
            """SELECT lp.*, c.name AS campaign_name FROM lead_packages lp
               JOIN campaigns c ON c.id = lp.campaign_id WHERE lp.id = ?""", (lead_package_id,),
        ).fetchone()
        return dict(row) if row else None

    def find_lead_package(self, provider: str, package_id: str, campaign_id: int) -> Optional[dict]:
        row = self.conn.execute(
            "SELECT * FROM lead_packages WHERE provider = ? AND package_id = ? AND campaign_id = ?",
            (provider, package_id, campaign_id),
        ).fetchone()
        return dict(row) if row else None

    def list_lead_packages(self, campaign_id: Optional[int] = None) -> list[dict]:
        sql = """SELECT lp.*, c.name AS campaign_name FROM lead_packages lp
                 JOIN campaigns c ON c.id = lp.campaign_id"""
        params: tuple = ()
        if campaign_id is not None:
            sql += " WHERE lp.campaign_id = ?"
            params = (campaign_id,)
        rows = self.conn.execute(sql + " ORDER BY lp.unlocked_at DESC", params).fetchall()
        return [dict(r) for r in rows]

    def royalty_settled(self, campaign_id: int, ref: str) -> bool:
        return self.conn.execute(
            """SELECT 1 FROM spend WHERE kind = 'royalty' AND campaign_id = ? AND ref = ?
               AND status = 'settled'""",
            (campaign_id, ref),
        ).fetchone() is not None

    def campaign_spend(self, campaign_id: int) -> dict:
        """Settled spend by kind, this month's committed spend, and pending count."""
        c = self.conn
        rows = c.execute(
            """SELECT kind, COUNT(*) AS n, COALESCE(SUM(amount_atomic), 0) AS total FROM spend
               WHERE campaign_id = ? AND status = 'settled' GROUP BY kind""",
            (campaign_id,),
        ).fetchall()
        month = c.execute(
            """SELECT COALESCE(SUM(amount_atomic), 0) AS total FROM spend
               WHERE campaign_id = ? AND status IN ('pending', 'settled') AND kind IN ('unlock', 'royalty')
                 AND created_at >= date_trunc('month', CURRENT_TIMESTAMP)""",
            (campaign_id,),
        ).fetchone()["total"]
        pending = c.execute(
            "SELECT COUNT(*) AS n FROM spend WHERE campaign_id = ? AND status = 'pending'",
            (campaign_id,),
        ).fetchone()["n"]
        by_kind = {r["kind"]: {"count": r["n"], "total_atomic": r["total"]} for r in rows}
        refunds = by_kind.get("refund_in", {}).get("total_atomic", 0)
        return {
            "by_kind": by_kind,
            # Net of refunds received from guarantee claims.
            "total_atomic": sum(v["total_atomic"] for k, v in by_kind.items() if k != "refund_in") - refunds,
            "refunds_atomic": refunds,
            "month_atomic": month,
            "pending": pending,
        }

    def prospect_spend(self, prospect_id: int) -> list[dict]:
        rows = self.conn.execute(
            """SELECT s.*, c.name AS campaign_name FROM spend s
               LEFT JOIN campaigns c ON c.id = s.campaign_id
               WHERE s.prospect_id = ? AND s.status = 'settled' ORDER BY s.created_at DESC""",
            (prospect_id,),
        ).fetchall()
        return [dict(r) for r in rows]

    def spend_allowance(self, user_id: int) -> int:
        row = self.conn.execute(
            "SELECT monthly_spend_allowance_atomic AS a FROM user_prefs WHERE user_id = ?", (user_id,),
        ).fetchone()
        return row["a"] if row else 0

    def set_spend_allowance(self, user_id: int, atomic: int, actor: Optional[CurrentUser]) -> None:
        with self.transaction() as c:
            c.execute(
                """INSERT INTO user_prefs (user_id, monthly_spend_allowance_atomic) VALUES (?, ?)
                   ON CONFLICT (user_id) DO UPDATE SET
                     monthly_spend_allowance_atomic = EXCLUDED.monthly_spend_allowance_atomic,
                     updated_at = CURRENT_TIMESTAMP""",
                (user_id, max(0, int(atomic))),
            )
            self._audit(c, actor, "spend.allowance", "user", user_id, {"atomic": int(atomic)})

    def user_month_spend(self, user_id: int) -> int:
        """What counts against a user's allowance this month (pending + settled)."""
        return self.conn.execute(
            """SELECT COALESCE(SUM(amount_atomic), 0) AS total FROM spend
               WHERE user_id = ? AND status IN ('pending', 'settled') AND kind IN ('unlock', 'royalty')
                 AND created_at >= date_trunc('month', CURRENT_TIMESTAMP)""",
            (user_id,),
        ).fetchone()["total"]

    def user_spend(self, user_id: int, limit: int = 10) -> dict:
        """A user's committed spend this month and their latest payments."""
        month = self.user_month_spend(user_id)
        rows = self.conn.execute(
            """SELECT s.*, c.name AS campaign_name FROM spend s
               LEFT JOIN campaigns c ON c.id = s.campaign_id
               WHERE s.user_id = ? AND s.status IN ('pending', 'settled', 'failed')
               ORDER BY s.created_at DESC, s.id DESC LIMIT ?""",
            (user_id, limit),
        ).fetchall()
        return {"month_atomic": month, "recent": [dict(r) for r in rows]}

    def pending_spend(self) -> list[dict]:
        """Payments awaiting onchain confirmation: sent with no settlement read back
        (these hold budget), or refunds a provider says it sent."""
        rows = self.conn.execute(
            """SELECT s.*, c.name AS campaign_name FROM spend s
               LEFT JOIN campaigns c ON c.id = s.campaign_id
               WHERE s.status = 'pending' ORDER BY s.created_at""",
        ).fetchall()
        return [dict(r) for r in rows]

    def resolve_spend(self, spend_id: int, status: str, tx_hash: str, actor: Optional[CurrentUser]) -> bool:
        """Settle or fail a pending payment after checking it onchain. False if not pending.

        Marking it failed releases its budget and lets the payment be retried.
        """
        if status not in ("settled", "failed"):
            raise ValueError("status must be settled or failed")
        if status == "settled" and not re.fullmatch(r"0x[0-9a-fA-F]{64}", tx_hash or ""):
            raise ValueError("A settled payment needs its 0x transaction hash")
        with self.transaction() as c:
            row = c.execute(
                """UPDATE spend SET status = ?, tx_hash = COALESCE(?, tx_hash),
                       error = CASE WHEN ? = 'failed' THEN 'Resolved as failed' ELSE NULL END,
                       updated_at = CURRENT_TIMESTAMP
                   WHERE id = ? AND status = 'pending' RETURNING id""",
                (status, tx_hash or None, status, spend_id),
            ).fetchone()
            if row is None:
                return False
            self._audit(c, actor, "spend.resolve", "spend", spend_id, {"status": status, "tx_hash": tx_hash})
        return True

    def set_ai_enabled(self, user_id: int, enabled: bool, actor: Optional[CurrentUser]) -> None:
        """Turn AI features on or off for one user (audited)."""
        c = self.conn
        with c.raw.transaction():
            c.execute(
                """INSERT INTO user_prefs (user_id, ai_enabled) VALUES (?, ?)
                   ON CONFLICT (user_id) DO UPDATE SET ai_enabled = EXCLUDED.ai_enabled,
                     updated_at = CURRENT_TIMESTAMP""",
                (user_id, int(enabled)),
            )
            self._audit(c, actor, "prefs.ai_enabled", "user", user_id, {"enabled": bool(enabled)})
